department-of-veterans-affairs/va-mobile-library

packages/components/src/utils/OSfunctions.tsx
packages/components/src/utils/translation/en.json

- Updated copy for leaving app prompt per the ACs
- Validated iOS/Android screen reader sounded good with the copy changes
iOS screenshot (similar in Android):
No testing on Web as the prompt doesn't appear.
- General
- Code
Changes do not warrant a new version [per the versioning guidelines](https://github.com/department-of-veterans-affairs/va-mobile-library#versioning-policy) as Link has still not officially been published.

[Feature] Update copy for leave app prompt

---

packages/components/package.json
packages/components/src/components/Icon/Icon.tsx
yarn.lock

Updated components to use assets package 0.3.0 [with updated icons](https://github.com/department-of-veterans-affairs/va-mobile-library/commit/4058744c15a656eef9df7757009b182e2bb778a0) for Alerts. Added doc indicating `fill2` prop will be deprecated in time as icon updates continue.
- Visual check
- Skipped Android, SVGs should be fine 
- Checked SVG path with inspector 
- General
- Code

[Feature] Update Icons for Alert

---

packages/components/src/components/Icon/Icon.tsx

- Since we will not have an Icon page on our documentation to link to, this updates the autogenerated docs in Storybook for the Icon component
- Adds some additional info on usage, link to assets package, and webpack setup
- Created follow up ticket #234 to update these docs once we've updated our Icons to align with VADS
N/A
- General
- Code

[CU] Update Icon Storybook docs

---

packages/components/package.json
packages/components/src/components/Link/Link.tsx

This PR serves as a minor bug fix ticket as well as the validation for the Link.  Tested the Link component in the app by replacing some phone, tty, attachment and links in Secure Messaging. 
Noticed that if a Link does not have a Box surrounding it, it will be horizontally centered. Removing the `justifyContent: center` in this PR aligns the Link left while maintaining other styling. Also noticed that the icon is not vertically aligned at larger text sizes but since that is a more complex fix, created ticket https://github.com/department-of-veterans-affairs/va-mobile-library/issues/240 to address it separately.
Tested iOS Voiceover and Android talkback on links and verified that a11y labels and a11y hints are identical. iOS screen recordings attached below. Android screen recording did …

[Bug] Fix horizontal alignment

---

packages/components/package.json
packages/linting/index.js
packages/linting/package.json

Adds deprecation warnings ClickForActionLink, ClickToCallPhoneNumber, and AttachmentLink to use new Link component from component library instead. Also bumps linting pakage version to 0.11.0 so that the next publish will be in sync with components package (0.12.0).
- 0.3.1-alpha.0
- 0.3.1-alpha.1
- 0.3.1-alpha.2
- General
- Code

[Feature] Link component - Update linting package

---

packages/components/src/components/Alert/Alert.stories.tsx
packages/components/src/components/Alert/Alert.tsx
packages/components/src/components/Button/Button.tsx
packages/components/src/utils/index.tsx

Created initial pass at Alert component.
- Created Alert component
- 4 variants with both light/dark mode color schemes
- Optional header, description, and children (custom react elements) to display as alert content
- Optional primary/secondary buttons for actions associated with the Alert
- Split off: Ticket #246 for adding support for expand/collapsible accordion form
- Created a basic Storybook story for testing with Alert
- Button component
- Updated Button to instead of filling out horizontal width with `alignSelf: 'stretch'` to use `width: '100%'` as it was noted working through Alert that `alignSelf: 'stretch'` will appear bugged (stretch out vertically) if it is nested within a View (or other element) with flexDirection of 'row' and there's space to do so
- Utilities
- Added new …

[Feature] Alert - Create Alert Component

---

packages/tokens/figma/dark.json
packages/tokens/figma/light.json
packages/tokens/src/tokens/color/component-dark.json
packages/tokens/src/tokens/color/component-light.json
packages/tokens/src/tokens/color/semantic-dark.json
packages/tokens/src/tokens/color/semantic-light.json

- Added 2 component tokens and 4 semantic tokens for the Segmented Control
- Ran `yarn tokens:build`
- Checked light.json, dark.json, and index.js files -- all tokens are in those files.
- General
- Code

Add tokens for Segmented Control

---

packages/components/src/components/Link/Link.test.tsx
packages/components/src/components/Link/Link.tsx

Replaces bold styling with background color for Link active state as per [figma design](https://www.figma.com/proto/Zzt8z60hCtdEzXx2GFWghH/branch/HRsHkww7nAqSdquMQ7uEZ4/%F0%9F%93%90-Component-Library?page-id=224%3A314&type=design&node-id=2186-478&viewport=1743%2C-866%2C0.74&t=lYrOBHRm2XOOBM8t-1&scaling=min-zoom). For light mode background is `grayDark` and dark mode it is `grayLighter`. Also added unit tests for the pressed state styling.
N/A
https://github.com/department-of-veterans-affairs/va-mobile-library/assets/786704/d5b0a885-8d23-4d61-a063-a9a150ba4b19
https://github.com/department-of-veterans-affairs/va-mobile-library/assets/786704/a5b0bc26-945f-450d-b4d1-3bae6df10db6
https://github.com/department-of-veterans-affairs/va-mobile-library/assets/786704/50287472-5486-4843-810c-126f4e31a …

[Feature] Update Link active state

---

packages/components/src/components/Alert/Alert.stories.tsx
packages/components/src/components/Alert/Alert.tsx

Updated Alert Storybook stories to [match what Jessica thought good in Slack](https://adhoc.slack.com/archives/C05DQPHUVNZ/p1713902470646879?thread_ts=1713810868.773319&cid=C05DQPHUVNZ).
- General
- Code
Changes do not warrant a new version [per the versioning guidelines](https://github.com/department-of-veterans-affairs/va-mobile-library#versioning-policy), only updating stories and documentation.

[Feature] Add Alert Storybook Stories

---

packages/components/package.json
packages/components/src/components/Link/Link.tsx

Added flexShrink to the style of the Text for the Link since otherwise [React Native Text component thinks it always has access to the full row width when nested within a row flexbox](https://www.bam.tech/article/why-my-text-is-going-off-screen). In the Link it does not due to the icon (if present) so it should shrink to fit.
- [0.15.1-beta.0](https://www.npmjs.com/package/@department-of-veterans-affairs/mobile-component-library/v/0.15.1-beta.0)
Appropriate length text goes right up to boundary (note, the text is "tes t" with a space and not wrapping mid-word):
When completing the word, wraps around as it pushes past the boundary:
- General
- Split to separate ticket and ticket is linked by …

[Bug] Link - Fix Text Wrapping

---

packages/components/src/components/Icon/Icon.tsx

Added `!` to value TS is incorrectly flagging as potentially undefined to tell it it is not undefined.
Verified VS Code no longer flags the instance with a red squiggle.
- General
- Code

[Bug] Fix TS complaint in Icon

---

packages/tokens/figma/dark.json
packages/tokens/figma/light.json
packages/tokens/src/tokens/color/semantic-dark.json
packages/tokens/src/tokens/color/semantic-light.json

Closes #178 
**Added 6 border tokens for button**
- vads-color-action-border-base-on-dark
- vads-color-action-border-base-on-light
- vads-color-action-border-default-active-on-dark
- vads-color-action-border-default-active-on-light
- vads-color-action-border-default-on-dark
- vads-color-action-border-default-on-light
**Added 8 foreground tokens for button**
- vads-color-action-foreground-base-active-on-dark
- vads-color-action-foreground-base-active-on-light
- vads-color-action-foreground-base-on-dark
- vads-color-action-foreground-base-on-light
- vads-color-action-foreground-default-active-on-dark
- vads-color-action-foreground-default-active-on-light
- vads-color-action-foreground-inverse-on-dark
- vads-color-action-foreground-inverse-on-light
**Added 10 surface tokens for button**
- …

[Feature] Add semantic tokens for button

---

packages/components/src/components/Alert/Alert.test.tsx
packages/components/src/components/Alert/Alert.tsx

Updated Alert success variant to have CheckCircle icon instead of Check to [align with VADS](https://design.va.gov/storybook/?path=/docs/uswds-va-alert--default#success). Updated success unit tests to reflect the checks and pass.
Checked iOS/Web/Android looked good in light and dark mode.
- General
- Code

[Enhancement] Update Alert success icon to align with VADS

---

packages/components/src/components/LoadingIndicator/LoadingIndicator.stories.tsx

Updates documentation URL for Loading indicator
N/A
N/a
- General
- Code

[Bug] Fix URL for loading indicator docs

---

packages/components/src/components/LoadingIndicator/LoadingIndicator.test.tsx

Added unit tests for Loading indicator component including:
- Basic tests
- Accessibility
- Light/dark mode
- With/without children
`yarn test` passes all new tests and failed as expected when changing expect statements to inaccurate values.
- General
- Code
Changes do not warrant a new version [per the versioning guidelines](https://github.com/department-of-veterans-affairs/va-mobile-library#versioning-policy) as they are only unit tests.

[Tests] Add Loading indicator unit tests

---

packages/components/src/components/Icon/Icon.stories.tsx

Added name/docUrl parameters for the generateDocs function for Icon pointing to page noted in ticket.
iOS/Android not applicable as they don't have the component doc pages. Checked web storybook link appears as expected.
- General
- Code
Changes do not warrant a new version [per the versioning guidelines](https://github.com/department-of-veterans-affairs/va-mobile-library#versioning-policy) as they are documentation only.

[Documentation] Add documentation site link for Icon component

---

packages/components/package.json
packages/components/src/components/Icon/iconList.ts
yarn.lock

- Bumps mobile-assets to 0.12.0 in component package.json
- Ran `yarn buildIcons` to rebuild Icon list and update imports in Icon component
- assets@0.11.1-alpha.0
https://github.com/department-of-veterans-affairs/va-mobile-library/assets/786704/1742197c-f0f2-4b0c-983a-b92c1a357a23
https://github.com/department-of-veterans-affairs/va-mobile-library/assets/786704/2e10d426-c7b5-4793-bdca-a265f055d37f
https://github.com/department-of-veterans-affairs/va-mobile-library/assets/786704/af516908-4db7-4232-8356-e351ddf5244f
https://github.com/department-of-veterans-affairs/va-mobile-library/assets/786704/d482e625-0ccf-400b-b93f-dddb1a810e0c
- General
- Split to separate ticket and ticket is linked by …

[Feature] Update Icon component for new Icons

---

.github/dependabot.yml
CHANGELOG.md

Adds dependabot config to check for changes to dependencies in our tokens `package.json` so that we can be alerted when VADS updates css-library. 
**Note:** We may want to update this to check for packages across our monorepo, but at the moment we have 50+ dependencies that are out of date. To avoid dependabot creating 50+ PRs, we should complete #378 and then revisit adding the rest of the repo to the dependabot version check.
Also includes dependabot security vulnerability PRs #352 and #354.
N/A
N/A
- General
- Code
If changes warrant a new version [per the versioning guidelines](https://github.com/department-of-veterans-affairs …

[CU] Add dependabot update check on tokens package

---

packages/components/src/assets/svgs/custom.svg
packages/components/src/components/Button/Button.tsx
packages/components/src/components/Icon/Icon.tsx
packages/components/src/components/LoadingIndicator/LoadingIndicator.tsx
packages/components/src/components/SegmentedControl/SegmentedControl.tsx

Updated Button, Icon, Loading indicator, and Segmented control components to leverage the useTheme hook and cleaned up legacy colors use as appropriate.
Additionally and unrelated to the ticket, removed the stroke from our custom SVG example since we do not support stroke so it could be misleading.
`yarn test` succeeds. Validated Web/iOS/Android look as expected for updated components
- General
- Code

[Feature] Update additional components to useTheme hook

---

packages/components/.npmignore
packages/components/.storybook/web/main.ts
packages/components/storybook/colors.stories.mdx

Closes #376 
- Added primitive, semantic, and component color tokens to Storybook
- Tokens are documented similarly to [Figma / doc site](https://department-of-veterans-affairs.github.io/va-mobile-app/design/Foundation/Design%20tokens/Color)
- General
- Code
Changes do not warrant a new version [per the versioning guidelines](https://github.com/department-of-veterans-affairs/va-mobile-library#versioning-policy) as they are Storybook related.

Spike/376 - Jessica - Add color tokens to Storybook

---

packages/components/src/components/Alert/Alert.tsx

- Increases spacing between header/description and description/link from 10 to 20
N/A
**Before/after:** 
- General
- Code

[Feature] Increase spacing between header and content, and content and buttons

---

packages/components/.npmignore
packages/components/global.d.ts
packages/components/package.json
packages/components/src/App.tsx
packages/components/src/components/Link/Link.tsx
packages/components/src/components/Snackbar/Snackbar.tsx
packages/components/src/index.tsx
yarn.lock

Created a proof of concept for the Snackbar component that works in both Storybook and flagship. This ticket mostly lays some groundwork, significant refinement will be made on implementation ticket for Snackbar including creating the custom display and getting into specifics where this PR leaves fairly general properties copied from flagship.
- [0.20.4-alpha.0](https://www.npmjs.com/package/@department-of-veterans-affairs/mobile-component-library/v/0.20.4-alpha.0)
Storybook (with 3 second duration for testing):
https://github.com/user-attachments/assets/55fb1cca-795f-4e3d-a72b-25fd6fadc6a9
Flagship (with 3 second duration for testing):
https://github.com/user-attachments/assets/8f7a30ea-7214-42bc-920b-2e62c8daefcb
Validated it worked as expected in iOS in Storybook. Validated it worked …

[Spike] Snackbar proof of concept

---

packages/tokens/figma/dark.json
packages/tokens/figma/light.json
packages/tokens/src/tokens/color/semantic-dark.json
packages/tokens/src/tokens/color/semantic-light.json

Closes #406 
- Added 2 new tokens for the Snackbar active states
- vads-color-action-foreground-inverse-active-on-light (references vads-color-base-light)
- vads-color-action-foreground-inverse-active-on-dark (references vads-color-base-dark)
- General
- Code

[Feature] Add tokens for Snackbar active states

---

packages/components/src/components/Snackbar/Snackbar.stories.tsx
packages/components/src/components/Snackbar/Snackbar.tsx

Added storybook story for the Snackbar component. There is a single story demonstrating a fairly standard case of a successful scenario that includes action button to "Undo" which can easily be modified (in web) to have: 
- `isError: true` to change the icon and action button to "Try again"
- Remove `onActionPressed` to remove the action button
In web, the story displays the Snackbar visual logic flat. 
In iOS/Android, the same story instead has a custom render logic which displays a Button and pressing the button brings up the Snackbar using actual handling logic.
Web:
https://github.com/user-attachments/assets/96f1ec20-6383-4d85-baef-1e4b39e4caee
iOS (Android behaves similar):
https://github.com/user-attachments/assets/c91cb88d-14b6-4731-be1c-d3f077bc71c6
Validated iOS/Android and web …

[Feature] Add Snackbar to Storybook

---

package.json
packages/components/src/components/Snackbar/Snackbar.stories.tsx
packages/components/src/components/Snackbar/Snackbar.tsx
packages/components/src/components/Snackbar/SnackbarProvider.tsx
packages/components/src/components/Snackbar/useSnackbar.tsx
yarn.lock

Reworked the Snackbar typing to be more clear.
Unrelated to ticket: added `prettier-eslint` package to base repo to resolve the Prettier ESLint plugin from getting an error when running instead of simultaneously handling both Prettier and ESLint formatting issues.
Spot checked each platform to confirm nothing was broken by type restructuring.
- General
- Code
While changes warrant a new version [per the versioning guidelines](https://github.com/department-of-veterans-affairs/va-mobile-library#versioning-policy), we are postponing Snackbar publish until later.

[Feature] Snackbar - Simplify Typing

---

packages/components/package.json
packages/components/src/components/Snackbar/Snackbar.stories.tsx
packages/components/src/components/Snackbar/Snackbar.tsx
packages/components/src/components/Snackbar/SnackbarProvider.tsx
packages/components/src/components/Snackbar/useSnackbar.tsx

Auto dismiss snackbar after 5 sec if screen reader is on and snackbar has no action provided
- Added `duration` and `setDuration` to `SnackbarContext`
- Added `SNACKBAR_DURATIONS` consts
- Cleaned up and added logic to `useSnackbar().show()` to auto-dismiss if screenreader and no action
- Added separate story for snackbar with and without action for easier accessibility testing for Brea
<details><summary>iOS screen reader auto-dismiss (no action)</summary>
https://github.com/user-attachments/assets/7ba3f33b-8770-4ce2-83c5-0a83ca8b97f2
</details>
<details><summary>iOS screen reader with action</summary>
https://github.com/user-attachments/assets/8d8298a5-ef11-40a9-931a-996e82248166
</details>
<details><summary>iOS no screen reader</summary> …

[Feature] Snackbar – Add auto-dismiss logic for screen readers when no action provided

---

packages/linting/index.js
packages/linting/package.json

Adds `react-native-toast-notifications` as a regexp pattern to deprecation warnings. Saves from adding each of the Toast imports separately and found that doing that wasn't entirely working anyway. 
Adding `snackbar` had no effect and will have to be manually removed from `global.d.ts` by the app team which should restore linting warnings about the global var.
- linting@0.18.1-alpha.0
- General
- Code

[Feature] Add 'react-native-toast-notifications' to linter deprecation warnings

---

packages/components/storybook/colors.stories.mdx
packages/tokens/figma/dark.json
packages/tokens/figma/light.json
packages/tokens/package.json
packages/tokens/src/tokens/color/semantic-dark.json
packages/tokens/src/tokens/color/semantic-light.json

- Added Checkbox tokens to semantic-light and semantic-dark
- vads-color-forms-border-default-on-dark / vads-color-forms-border-default-on-light
- vads-color-forms-border-error-on-dark / vads-color-forms-border-error-on-light
- vads-color-forms-border-subtle-on-dark / vads-color-forms-border-subtle-on-light
- vads-color-forms-border-active-on-dark / vads-color-forms-border-active-on-light
- vads-color-forms-foreground-active-on-dark / vads-color-forms-foreground-active-on-light
- vads-color-foreground-subtle-on-dark / vads-color-foreground-subtle-on-light
- vads-color-foreground-error-on-dark / vads-color-foreground-error-on-light
- General
- Split to separate ticket and ticket is linked by …

[Feature] Add Checkbox tokens

---

packages/components/package.json
packages/components/storybook/colors.stories.mdx
yarn.lock

- Update tokens version number in `components/package.json`
- Added `gray-2` and `gray-60` tokens to Storybook (previously missing)
- Added Checkbox tokens from #472 to Storybook
- General
- Code

[Feature] Add Checkbox tokens to Storybook

---

.github/ISSUE_TEMPLATE/vads-icon.md
.github/ISSUE_TEMPLATE/vads-token.md

Adds 2 issue templates for follow-up work to update our package with VADS token or icon updates.

Templates for VADS icon and tokens follow up work 

---

packages/components/package.json
packages/components/src/components/Alert/Alert.tsx
packages/components/src/components/Snackbar/Snackbar.tsx
packages/components/src/components/Spacer/Spacer.test.tsx
packages/components/src/components/Spacer/Spacer.tsx
packages/tokens/build.js
yarn.lock

- Updates Spacer component to use new spacing tokens from #447 
- Default size is now vadsSpaceSm (12)
- **Note:** Alert was the only component using Spacer with the default value of 10. Confirmed that it is to be updated to vadsSpaceSm (12) as per [Figma doc](https://www.figma.com/design/XQwpzcNSGyGJN4nXDPoEj0/Design-Tokens---%F0%9F%94%8D-Design-System---VA-Mobile?node-id=238-927&node-type=instance&t=UiWJGxavr7qams0k-0) and spacing above buttons in expandable alert is to be updated to vadsSpace4xl (36) vs the old 34
- Updated any components using Spacer with values passed to use new size variants
- components@0.23.1-alpha.1
- General
- Split to separate ticket and ticket is linked by relevant …

[Feature] Update Spacer component to use spacing tokens

---

packages/components/package.json
packages/components/src/components/Icon/iconList.ts
yarn.lock

Updated assets package in components package and ran script to rebuild the icons to include ArrowCircleRight.
- General
- Code
While changes warrant a new version [per the versioning guidelines](https://github.com/department-of-veterans-affairs/va-mobile-library#versioning-policy), flagship is largely not using our Icon component yet so there's no time pressure to make this icon available so this ticket will defer publishing to be bundled with next package publishing.

[Icons] Add ArrowCircleRight icon to components

---

packages/tokens/figma/dark.json
packages/tokens/figma/light.json
packages/tokens/package.json
yarn.lock

Updated css-library in tokens package and ran the tokens build script to update accordingly.
Ticket #482 created after noting the non-intuitive sorting verifying the `.d.ts` files had updated as expected.
Inspected the outputs in the `figma` and `dist` folders appear as expected with the new tokens (and renamed token).
- General
- Code

[Tokens] Add Checkbox color tokens

---

packages/components/package.json
packages/components/src/components/Alert/Alert.tsx
packages/components/src/components/Button/Button.tsx
packages/components/src/components/Link/Link.tsx
packages/components/src/components/LoadingIndicator/LoadingIndicator.tsx
packages/components/src/components/SegmentedControl/SegmentedControl.tsx
packages/components/src/components/Snackbar/Snackbar.tsx

- Updated Alert, Button, Link, Segmented control, and Snackbar to use the spacing tokens
- ~~Loading indicator did not require changes as it used the default spacing size which was updated by #448~~
- Loading indicator updated during PR to use `xs` (8) spacers between icon/text and text/children content
- Fixed a minor design inconsistency with Segmented control where it had no horizontal padding so segment labels could get very close before wrapping
- Created #491 to address further improvements
- Fixed a minor bug noted with Snackbar where it was applying the `gap` property to both row and column flex so it had minor 5 extra padding between message and buttons causing it to wrap slightly sooner than it should've
- Reworked setting of height for icon containers to align with the text …

[Code Upkeep] Update components to use spacing tokens

---

packages/components/src/components/Checkbox/Checkbox.stories.tsx

- Update figma and documentation links (docs link will be updated once docs are moved to Design System section in #194)
- Reduce number of stories and rename after discussion with @jessicawoodin 
N/A
https://github.com/user-attachments/assets/caa04b31-d739-40d4-b5fa-68f7bc8c252e
- General
- Code

[Feature] Checkbox Storybook Stories

---

packages/tokens/README.md

Update tokens README.md to mention useTheme hook usage. Previously it mentioned that a hook may be made available in the future.
N/A
N/A
N/A
- General
- Code

[Docs] Update tokens README.md to mention useTheme hook usage

---

packages/components/src/components/Checkbox/Checkbox.stories.tsx
packages/components/src/components/CheckboxGroup/CheckboxGroup.stories.tsx

Updated Checkbox group component storybook stories to align with design expectation. 
Also added a little (8px) margin to Checkbox (group) component stories to display better in mobile (no longer have the Header/hint/etc. flush against the side of the screen w/ component using full width).
Removed the Figma/design links from Checkbox (group) components as determined [in a slack thread](https://dsva.slack.com/archives/C07KFQ3U6QH/p1727803795889379). 
- General
- Code
Changes do not warrant a new version [per the versioning guidelines](https://github.com/department-of-veterans-affairs/va-mobile-library/blob/main/documentation/versio …

[Feature] Checkbox group Storybook

---

packages/components/src/components/Checkbox/Checkbox.tsx
packages/components/src/components/CheckboxGroup/CheckboxGroup.stories.tsx
packages/components/src/components/CheckboxGroup/CheckboxGroup.tsx

Fixes a couple overlooked things in CheckboxGroup implementation
- Allows for checkbox item descriptions to be passed to CheckboxGroup
- Replace spacing token for border radius with absolute number until we have radius tokens available
- General
- Code

[Feature] CheckboxGroup – Add item descriptions

---

packages/components/storybook/SpacingTable.tsx
packages/components/storybook/spacing.stories.mdx

Adds a Spacing tokens storybook page with a table of tokens and visual example, similar to our color tokens page and [VADS's docs](https://design.va.gov/foundation/spacing-units#primitive).
N/A
- General
- Code

Add spacing tokens mdx story

---

packages/components/.npmignore
packages/components/jest/utils.ts
packages/components/src/components/Checkbox/Checkbox.test.tsx
packages/components/src/components/Checkbox/Checkbox.tsx
packages/components/src/components/CheckboxGroup/CheckboxGroup.test.tsx
packages/components/src/components/CheckboxGroup/CheckboxGroup.tsx
packages/components/src/components/shared/FormText.test.tsx
packages/components/src/utils/jest.tsx

- Add unit tests for Checkbox, CheckboxGroup, and FormText
- Adds forgotten testID implemtnation to CheckboxGroup and Checkbox
- Checkbox and CheckboxGroup tests check for the existence of provided text while FormText tests for dark/light mode styling and accessibility labels.
N/A
N/A
N/A
- General
- Code
Does not warrant publish

[Tests] Checkbox, CheckboxGroup, FormText

---

packages/tokens/figma/dark.json
packages/tokens/figma/light.json
packages/tokens/src/tokens/color/semantic-dark.json
packages/tokens/src/tokens/color/semantic-light.json

- Added border-strong and border-subtle color tokens to light/dark mode files
- General
- Code

[Feature] Add border tokens

---

packages/components/.storybook/web/preview-head.html
packages/components/package.json
packages/components/src/App.tsx
yarn.lock

Update components package to load Bitter-Regular font.
- Update to mobile-assets 0.14.0 which contains Bitter-Regular.ttf
- Add Bitter-Regular to useFonts hook in App.tsx
- Add Bitter-Regular to stylesheet for Storybook web
- General
- Code

[Feature] Add Bitter-Regular font

---

packages/components/package.json
packages/components/src/components/Text/Text.stories.tsx
yarn.lock

- Update to use mobile-tokens v0.22.0 with fixed bottom margin for headings
- Left align Text component in Storybook to avoid confusion regarding text alignment
- Reenable tone prop in Display story
- General
- Code

[Bug] Typography – Fix Heading margin bottom, Text stories

---

.github/workflows/publish-documentation.yml

The publish-documentation.yml workflow was failing due to a deprecated version of upload artifact. This PR updates it from v2 to v3.
- General
- Code

[Chore] Fix deprecated upload artifact

---

.github/workflows/publish-documentation.yml

Upgraded deploy-pages to v4 to see if this allows the docs to be published.
- General
- Code

[Chore] Updated deploy-pages to v4

---

packages/components/src/components/Alert/Alert.tsx
packages/components/src/components/Text/Text.tsx

Moved the responsibility of specifying the heading role from the Text component to the Alert component.
- General
- Code

[Bug] Fix VoiceOver for Alert headings

---

packages/components/src/components/Alert/Alert.tsx

The Alert component icon view style needed to account for cases where there is no header in order to align it correctly with the first line of the description text.
Before/after:
- General
- Code

[Bug] Fix Alert icon alignment when no header is present

---

.github/CODEOWNERS
packages/assets/package.json
packages/components/package.json
packages/linting/package.json
packages/tokens/package.json

Updating the CODEOWNERS file and packages to reflect the new Design System & Forms team now owns the mobile components/design system.

Transition repo ownership from mobile platform to design system & forms team

---

.github/pull_request_template.md

Updated PR template.
None.
N/A
N/A

Readd cross-repo ticket linking for Design System & Forms team ticket repo

---

packages/components/.storybook/main.ts

**[Ticket #4174](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/4174)**
After merging the Storybook 9 upgrade to main, it broke the production Web Storybook. Pushing this as an attempted fix since apparently permissions don't allow manually deploying anymore (from local or configuring the deploy to run against a branch).
In production after Storybook 9 upgrade:
Validated things still worked with Web Storybook locally. Changes only modified the web Storybook config and wouldn't effect iOS/Android.
- ~Tested on iOS~ 
- ~Tested on Android~ 
None, urgent fix that can only be tested in main.
Changes do not warrant a new version [per the versioning guidelines](https://github.com/department-of-veterans-affairs/va-mobile-library/ …

[Hotfix] Production Web Storybook issue
