department-of-veterans-affairs/va-mobile-library

- packages/components/src/utils/OSfunctions.tsx
**[Ticket #170](https://github.com/department-of-veterans-affairs/va-mobile-library/issues/170)**
- Components integration [failed](https://github.com/department-of-veterans-affairs/va-mobile-library/actions/runs/8055708787). TypeScript doesn't like the absolute import of Link
- Updated to use relative import instead
- General
- Code
> [BUG] Fix TS error – Update LinkAnalytics import to relative

- packages/components/src/components/Link/Link.stories.tsx
- packages/components/src/components/Link/Link.tsx
- Added attachment type support to Link:
- Prefills PaperClip icon
- Required onPress logic from app
- Includes a11yValue prop to support "[position #] of [total #]" list logic (or whatever custom string an app wants to pass if having preferred language for lists)
- Removed inline type support and related cleanup per team decision to not move forward with it for now
iOS:
https://github.com/department-of-veterans-affairs/va-mobile-library/assets/8690976/ca8c3032-8997-4c22-9f4a-82df4a5b5d3f
Android:
https://github.com/department-of-veterans-affairs/va-mobile-library/assets/8690976/1bd937b6-b27d-4ed8-be21-8cd459079e6c
- General
- …
> [Feature] Link - Add attachment type support

- packages/components/src/components/Link/Link.tsx
- Added hitSlop of 7 to RN Pressable that expands the pressable area 7 in all directions to achieve the minimum 44px height press target (with the 30px line height of text)
- React Native automatically handles if that touch target causes conflicts with other display elements
- Added style props to the View wrapping the Icon (if present) so that:
- It has the same minimum height of the text (line height 30) so that the icon is centered vertically
- Icon remains aligned with the first line if the text is long enough to wrap
- Icon can still scale fine both from OS scaling and manually increasing size with height/width parameters
iOS (Android similar) screenshot showing touch target height 44 (30 + 7 top + 7 bottom):
Web showing alignment for long text + icon box keeping it aligned: …
> [Feature] Link - Visual QA Updates/Fixes

- packages/components/src/components/Alert/Alert.stories.tsx
- packages/components/src/components/Alert/Alert.tsx
- packages/components/src/components/Link/Link.tsx
Add analytics support by adding passthrough functions for expand and collapse. Analytics for buttons should already be covered by the onPresses for each button.
This also includes a fix for the Link background color getting stuck onPress
N/A
https://github.com/department-of-veterans-affairs/va-mobile-library/assets/786704/cb63d3eb-4b5a-40df-9214-ab7c0d9724c0
https://github.com/department-of-veterans-affairs/va-mobile-library/assets/786704/88d94fc2-ca2a-48e1-9abc-5fbbced5e50b
https://github.com/department-of-veterans-affairs/va-mobile-library/assets/786704/5df1a622-ba63-41b4-82e8-19815fd77663
- General
- Code
If changes warrant a …
> [Feature] Add analytics passthroughs for Alert

- packages/components/src/components/Alert/Alert.test.tsx
- packages/components/src/components/Alert/Alert.tsx
- packages/components/src/components/Button/Button.test.tsx
Adds the following unit tests for Alert:
- Check for rendering of header, description, children, buttons
- Verify colors for each variant in light and dark mode
- Expandable variants
- Analytics passthroughs
This PR also renames the `testId` prop in Alert to `testID` to be consistent the other components and fixes one of the Button tests to use queryByText instead of the async findByText.
Note: Moved accessibility tests to #279 since we'll want to configure jest matchers
N/A
N/A, they're unit tests
- General
- Code
If changes warrant a new version [per the versioning guidelines](https://github.com/department-of-veterans-affairs/va …
> [Feature] Alert unit tests

- packages/tokens/figma/dark.json
- packages/tokens/figma/light.json
- packages/tokens/src/tokens/color/semantic-dark.json
- packages/tokens/src/tokens/color/semantic-light.json
Closes #331 
**Added 10 tokens to semantic-light**
- vads-color-foreground-inverse-on-light
- vads-color-surface-inverse-on-light
- vads-color-feedback-border-info-on-light
- vads-color-feedback-border-success-on-light
- vads-color-feedback-border-warning-on-light
- vads-color-feedback-border-error-on-light
- vads-color-feedback-surface-info-on-light
- vads-color-feedback-surface-success-on-light
- vads-color-feedback-surface-warning-on-light
- vads-color-feedback-surface-error-on-light
**Added 5 tokens to semantic-dark**
- vads-color-foreground-inverse-on-dark
- vads-color-surface-inverse-on-dark
- vads-color-feedback-border-info-on-dark
- vads-color-feedback-border-success-on-dark
- vads-color-feedback-border-error-on-dark
N/A
N/A
- General …
> [Feature] Add tokens for Snackbar and Alert components

- packages/linting/index.js
- packages/linting/package.json
- Added Loading indicator linting rule to linting package against the LoadingComponent app-level component
- Bumped linting version to 0.17.1 so it'll align with components' package 0.18.0 for releasing the Loading indicator when publishing in main
- [0.15.1-alpha.0](https://www.npmjs.com/package/@department-of-veterans-affairs/eslint-config-mobile/v/0.15.1-alpha.0)
```
/Users/timroettger/Coding/VA-Workspace/va-mobile-app/VAMobile/src/components/CommonErrorComponents/CallHelpCenter.tsx
8:1  warning  AlertBox from components is deprecated. Use Alert from @department-of-veterans-affairs/mobile-component-library instead  deprecate/import
/Users/timroettger/Coding/VA-Workspace/va-mobile-app/VAMobile/src/components/CommonErrorComponents/DowntimeError.tsx
6:1  warning  AlertBox from components …
```
> [Linting] Add Loading indicator linting rule

- packages/components/src/components/Icon/Icon.test.tsx
Added 8 new Icon unit tests around the `fill` property testing:
- 4 categories: 
- Single string (does not change with light/dark mode)
- "default" colors
- "base" colors
- Custom light/dark mode color object
- Light/dark mode for each
Made minor adjustments to existing tests to simplify and/or improve them.
`yarn tests` passes with all new Icon tests. Draft tested different `expect` values caused failures as expected.
- General
- Code
Changes do not warrant a new version [per the versioning guidelines](https://github.com/department-of-veterans-affairs/va-mobile-library#versioning-policy) as they are purely unit tests.
> [Tests] Icon - Enhance Unit Tests

- documentation/releaseProcess.md
Adds documentation about our release process to the documentation site, outlining cadence, automation, git tagging, naming, change logs, and notifications.
N/A
- General
- Code
> [Docs] Add documentation for release process

- packages/components/package.json
- packages/components/src/components/Snackbar/Snackbar.stories.tsx
- packages/components/src/components/Snackbar/Snackbar.tsx
Added two props to the outermost container of the Snackbar display, one for each iOS and Android. Both effectively say the element should be focusable over other views (e.g. the ones below them).
Also added story documentation/a11y tweaks I'd made for a prior ticket but forgot to commit before merging.
- [0.21.1-alpha.5](https://www.npmjs.com/package/@department-of-veterans-affairs/mobile-component-library/v/0.21.1-alpha.5)
iOS (first with fix commented out demoing the tap through the Snackbar then "Refresh" around 16 seconds is with fix enabled):
https://github.com/user-attachments/assets/ae1f9ee9-8109-4b2c-b8ed-a45ee8b4c9c5
Android (first with fix commented out demoing the tap through the Snackbar then around 17 seconds is with fix enabled): …
> [Feature] Prevent screen reader from focusing content behind Snackbar

- packages/components/src/components/Icon/Icon.tsx
- packages/components/src/components/Link/Link.stories.tsx
- packages/components/src/components/Link/Link.test.tsx
- packages/components/src/components/Link/Link.tsx
- packages/components/src/utils/hooks/useExternalLink.ts
Efforts to make code more defensive against crashes:
1. Updated Link _onPress logic to no longer be async
- Likely legacy carryover from flagship component that uses async for adding to calendar (as it needs to query device calendar permissions), design system Link omitted calendar as it necessitates native code so should not be relevant
2. Updated Icon component to allow a null passthrough and made the Link use it
- Was noted as a potential error spot for the more/fewer hooks between renders as the no icon Link would return null while an icon-having Link would return the Icon component which contains hooks
- With the null passthrough, it will always be "rendered" so the hooks should remain consistent
- This adjustment also necessitated pulling the aligning the icon with the first row of …
> [Bug] Link - Flagship crash mitigation efforts

- packages/components/package.json
- packages/components/src/components/Spacer/Spacer.tsx
- packages/components/src/components/Text/Text.stories.tsx
- packages/components/src/components/Text/Text.tsx
- packages/components/src/index.tsx
- packages/components/src/utils/index.ts
- packages/components/src/utils/tokens.ts
- yarn.lock
Implementation of a new Text component that displays text based on our typography tokens
- Supports the following variants: body, heading, display, and navigation
- Allows for different size props for body and heading: xs, sm, md, lg
- Defaults to body medium if no variant or size is provided
- Has bottomSpacing prop that accepts different spacing tokens when something other than the default paragraph spacing is desired
- Includes a11y override and color override  
- components 0.27.1-alpha.0
<details><summary>Web</summary>
https://github.com/user-attachments/assets/36ae606e-94e1-40f8-989f-cad3b45f6262
</details>
<details><summary>iOS</summary>
https://github.com/user-attachments/assets/b4f7308a-fe10-44bf-8d94-57367d974c42
</details>
<details><summary>Android</summary> …
> [Feature] Text component

- packages/tokens/package.json
- packages/tokens/src/tokens/font/typography.json
In #550, @jessicawoodin noticed that that bottom spacing for headings was incorrect. This PR updates the values in the `typography.json` tokens to match the [Figma values](https://www.figma.com/design/Zzt8z60hCtdEzXx2GFWghH/%F0%9F%93%90-Component-Library---Design-System---VA-Mobile?node-id=7119-291&t=KtARQdM962OtZBip-4).
There will be a follow-up PR (#608) to update the component library to used the updated tokens.
- tokens-0.21.1-alpha.0
- General
- Code
If changes warrant a new version [per the versioning guidelines](https://github.com/department-of-veterans-affairs/va-mobile-library/blob/main/documentation/versioning.md) and …
> [Bug] Typography – Fix heading bottom margin

- packages/tokens/figma/dark.json
- packages/tokens/figma/light.json
- packages/tokens/src/tokens/color/semantic-dark.json
- packages/tokens/src/tokens/color/semantic-light.json
- Added:
- border-focus
- forms-border-success
- feedback-foreground-info
- feedback-foreground-error
- Removed:
- foreground-error
- General
- Code
> [Tokens] Add new tokens

- packages/components/package.json
- packages/components/storybook/colors.stories.mdx
- yarn.lock
- Update components to use tokens package 0.21.0. 
- Update storybook color docs to include new color tokens:
- **Primitive**
- uswds-system-color-green-cool-vivid-30
- uswds-system-color-gold-vivid-40
- **Semantic**
- vads-color-feedback-foregound-success-on-dark: uswds-system-color-green-cool-vivid-30
- vads-color-feedback-foregound-warning-on-light: uswds-system-color-gold-vivid-40
- vads-color-feedback-foregound-success-on-light: uswds-system-color-green-cool-vivid-50
- vads-color-feedback-foregound-warning-on-dark: uswds-system-color-gold-vivid-30
- General
- Code
If changes warrant a new version [per the versioning …
> [Tokens] Update components to use tokens package 0.21.0.  Update Storybook color docs

- packages/components/package.json
- packages/components/src/components/Snackbar/useSnackbar.tsx
Added memoization to the `useSnackbar` hook by utilizing `useCallback` and `useMemo`. This prevents the snackbar from being re-rendered when utilized inside a `useEffect` hook by the caller, which could have the undesirable effect of leaving the snackbar visible when it was intended to be hidden.
- [0.30.1-alpha.0](https://www.npmjs.com/package/@department-of-veterans-affairs/mobile-component-library/v/0.30.1-alpha.0)
These before/after videos show the issue in the VA Mobile app. Notice how in the 'Before' video the snackbar does not correctly get dismissed when backing up a screen.
https://github.com/user-attachments/assets/b00aa408-91cb-469d-96ed-4372d66a070b
https://github.com/user-attachments/assets/6471aa78-c914-4b3f-b3f3-cda4d63f9ad4
Testing was performed in the VA Mobile app using …
> [Enhancement] Add useMemo and useCallback to useSnackbar Hook

- packages/components/package.json
- packages/components/src/components/Alert/Alert.tsx
Removed the `role="heading"` property from the Alert component as this is already specified in the child Text component by virtue of the `variant="heading` property.
- [0.30.1-alpha.2](https://www.npmjs.com/package/@department-of-veterans-affairs/mobile-component-library/v/0.30.1-alpha.2)
Tested library separately. Also verified this allowed the VA Mobile App unit tests to function properly.
- General
- Code
> [Bug] Fix duplicate heading roles in Alert component

- packages/components/package.json
- packages/components/src/components/LoadingIndicator/LoadingIndicator.tsx
Replaced repetitive animation firing in the LoadingIndicator with a loop and added a cleanup function.
- [0.30.1-alpha.1](https://www.npmjs.com/package/@department-of-veterans-affairs/mobile-component-library/v/0.30.1-alpha.1)
Tested library on Android, iOS and Web. Also incorporated package into VA Mobile app and performed manual tests as well as detox/e2e tests.
- General
- Code
> [Enhancement] Improve loading indicator animation loop and cleanup

- packages/components/src/components/SegmentedControl/SegmentedControl.tsx
- packages/components/src/utils/translation/en.json
On iOS, the SegmentedControl did not correctly announce the state or the role of each tab contained within it. After extensive research, this looks to be an issue with either React Native and/or iOS itself. To mitigate the problem the SegmentedControl was modified to supply the text that VoiceOver should speak. Note that this is not an issue on Android.
N/A
These videos were created using the Accessibility Inspector that comes with Xcode. Turn up your sound to hear the before/after differences with VoiceOver.
https://github.com/user-attachments/assets/6c16e5f5-9ddf-4dbf-b122-ab44ade65088
https://github.com/user-attachments/assets/80d972bc-68fe-4378-af87-4a59ce6eeebd
- General
- Split to …
> [Bug] Fix VoiceOver for SegmentedControl

- packages/components/package.json
- packages/components/src/components/Alert/Alert.test.tsx
- packages/components/src/components/Button/Button.test.tsx
- packages/components/src/components/LoadingIndicator/LoadingIndicator.test.tsx
- packages/components/src/components/SegmentedControl/SegmentedControl.test.tsx
- packages/components/src/components/SegmentedControl/SegmentedControl.tsx
- packages/components/src/utils/translation/en.json
- yarn.lock
Feature: **[Ticket 491](https://github.com/department-of-veterans-affairs/va-mobile-library/issues/491)**
Bug: **[Ticket 4514](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/4514)**
Also related: **[Ticket 4174](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/4174)**
Updated the internals for the Segmented control button to native via React Native instead of using the `styled-components` 3rd party library.
Also fixed the bug added by #625 where VoiceOver reads "selected" twice.
Details:
- Removed the `styled-components` dependency and corresponding `jest-styled-components` dependency
- Removed custom accessibility handling added by #625 
- Also removed associated translations that are no longer used
- …
> [Feature] Revamp Segmented control internals to native
